### ISSUE TITLE
Command for publish auto-translate config

### ISSUE THREAD

**Issue by alexsalramxr** [devaslanphp/auto-translate#1]
Hi.

I've installed the package in my REST API, then I've try to run the `php artisan vendor:publish --tag=auto-translate` command but the terminal indicates me that tag not found with this name.

Any solution for this?

Here is the error:
![imagen](https://user-images.githubusercontent.com/36974510/213565694-28d8ffd5-c638-4e9e-96a1-c8d7292acd72.png)

**Comment by heloufir** [comment]
My bad, it's a documentation error, you need to execute `php artisan vendor:publish --tag=auto-translate-config`

I updated the docs.

**Comment by alexsalramxr** [comment]
I have the same issue, the tag doesn't exist.

![imagen](https://user-images.githubusercontent.com/36974510/213575313-a8b035ae-63bf-4579-bbdb-db16b8952dee.png)

**Comment by heloufir** [comment]
If you execute `php artisan vendor:publish --tag=auto-translate-config` what is the results in the terminal?

**Comment by alexsalramxr** [comment]
I get the same message from the first comment

Here:

![imagen](https://user-images.githubusercontent.com/36974510/213578151-0792f1e0-8aeb-4906-8487-501f13f214b6.png)

**Comment by heloufir** [comment]
Just to be sure all is installed, please follow the below steps:
- `composer require devaslanphp/auto-translate`
- `php artisan optimize:clear`
- `composer dump-autoload`
- `php artisan vendor:publish --tag=auto-translate-config`

**Comment by alexsalramxr** [comment]
I've follow all steps but it's the same issue, it didn't find the config tag.

**Comment by heloufir** [comment]
Weird, I got the same issue on a new project, but not my old one.

To get it working you need to add the provider into your `config/app.php`, like the following : 

```php
// config/app.php

//...

'providers' => [
      // ...

      \Devaslanphp\AutoTranslate\AutoTranslateProvider::class,
],

// ...
```

After that you can publish the config file.

**Comment by alexsalramxr** [comment]
It worked for me, it's because I'm using the latest version of laravel 9.

Thank you.
